Request Android Storage permission automatically when they aren't available
jfversluis/FilePicker-Plugin-for-Xamarin-and-Windows pull request #109
Opened 2018-11-15 12:04 UTC by ChristianKleineidam

### Description of Change ###

When the permissions aren't available in Android API level >=23 they app now asks the user to grant the permission instead of throwing an error. 

### Platforms Affected ### 
- Android

2018-11-15 14:23 UTC, vividos commented
Thanks for your contribution! I'll add some review comments soon.

2018-11-17 00:53 UTC, Happypig375 requested changes

2018-11-17 00:53 UTC, Happypig375 commented on src/Plugin.FilePicker/Plugin.FilePicker.Android/FilePickerActivity.cs
> +                this.context.PackageName) == Permission.Granted)
Is this meant to say `!= Permission.Granted`?

2018-11-18 20:08 UTC, ChristianKleineidam commented
(I'm just starting at contributing to Github projects, so if I'm doing something suboptimal I'm happy for feedback)
I created edits for doing the right thing after Permission.Granted. I'm also added the comment for RequestStorage (and used PascalCase).

2018-11-18 20:50 UTC, vividos approved these changes

2018-11-18 20:52 UTC, vividos commented
@ChristianKleineidam No, it's all good. My comments were just review of the code. I'll test this change when it's merged. I will also remove checking for permission in the sample, now that the check is inside the plugin.

2018-11-19 00:07 UTC, Happypig375 approved these changes

2018-11-20 18:48 UTC, merged

2018-11-20 19:25 UTC, vividos commented
This PR is available in NuGet package 2.0.132-beta.